version: "3"
services:
  database:
    image: postgres:10.17
    env_file:
      - "./database.env"
    environment:
     - "POSTGRES_DB=node_challenge" 
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgres
  app:
    build: ./api/.
    image: app
    container_name: app
    ports: 
      - "8080:8080"
    depends_on:
      - database
      - migration
  migration:
    image: app
    command: yarn typeorm migration:run
    depends_on:
      - database
      - frontend
  frontend:
    build: ./frontend/.
    image: frontend
    container_name: frontend
    ports:
      - "4200:80"

volumes:
  pg-data:
